### ISSUE TITLE
stava on NetBSD

### ISSUE THREAD

**Issue by voidpin** [simeg/stava#8]
Hej!

Här är `stava` i min NetBSD maskin.

![2020-11-27-143503_1366x768_scrot](https://user-images.githubusercontent.com/35956139/100456817-433fad00-30c1-11eb-9243-2308242184b6.png)

Jag har just paketerat detta och "push" till wip-repo (work in progress).
För att kunna flytta den till "main" skulle jag behöva en github release/tag.

Trevlig helg :)

**Comment by simeg** [comment]
Hej @voidpin.

Klart! Trevlig helg!

**Comment by voidpin** [comment]
@simeg Tack!
Merged, https://mail-index.netbsd.org/pkgsrc-changes/2020/11/28/msg224662.html

Är det möjligt att få en release/tag i github för kommande releases i crates.io?

Nu räcker det med `pkgin install stava` för att installera detta i NetBSD ;)

**Comment by simeg** [comment]
Coolt! Absolut, det fixar jag.
